### PR TITLE
Link to firmware-open in project README

### PR DESCRIPTION
**Pull request by yujiri8**

### CODE REVIEW

**Comment by crawfxrd** [comment]
This is subproject of firmware-open. If you want a list of dependencies, look at [`scripts/deps.sh`](https://github.com/system76/firmware-open/blob/fb9d759338c570265639553074a8c21fffb7f926/scripts/deps.sh).

**Comment by yujiri8** [comment]
Oh! In that case, shouldn't that fact be mentioned in the readme?

**Comment by crawfxrd** [comment]
You can make a mention of firmware-open at the top.

**Comment by yujiri8** [comment]
Alright, I updated the PR. How's this?

**Comment by yujiri8** [comment]
Bump?

**Comment by jacobgkau** [comment]
firmware-update is used to update firmware on other models running closed firmware (not firmware-open), so I'm not sure how much sense it makes to refer to this as a subproject of firmware-open.

**Comment by jacobgkau** [comment]
Oh, I see what's going on here. If we'd rather consider this a sub-project now instead of having its own list of dependencies, that's fine.

**Review by jacobgkau — APPROVED** [review]
Approving based on Tim's comments and the fact that this is included in firmware-open as a submodule. We may want to clarify in the future that it's not _just_ used for firmware-open, but the readme already mentions the private firmware repo (which also lists this as a submodule), so I don't think this is misleading.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
