### PR TITLE
Do cold reboot on success instead of shutdown

### PR DESCRIPTION
**Pull request by crawfxrd**
Remove the need to physically power on the machine after applying updates.

### CODE REVIEW

**Comment by leviport** [comment]
Does this apply to all machines, other than ones that use capsule update? Open firmware laptops appear to still be shutting down for me.

**Comment by crawfxrd** [comment]
Systems using System76 EC still do the watchdog reset, which causes a poweroff.

**Comment by jacobgkau** [comment]
I hoped this might eliminate the double-power-on requirement for Open EC laptops, but it seems that I still need to press the power button twice after the flash is done.

**Comment by leviport** [comment]
Looks like pang12 and major-r4 also still shut down after flashing. I'll try a few more proprietary firmware systems in case both of them just have something else going on.

**Review by leviport — APPROVED** [review]
I tried pang10, then (re)discovered that it does capsule updates, so this doesn't apply to it and it shuts down after flashing. 

I then dug out a gaze13, and it reboots after updating, so it looks like this works. I'm not sure this change will be appreciated by many, since it applies to such mature hardware, but I'm approving it since it works the way I'd expect it to.

**Comment by crawfxrd** [comment]
The flash utils themselves may be forcing a shutdown, and may not have a way to change the behavior.

**Comment by leviport** [comment]
I'll have to test thelio-b2 specifically since that workaround appears to have been added for a specific reason.

**Comment by crawfxrd** [comment]
Looks like the `ResetSystem` call can just be dropped, since it will return to `efi_main` which will do the cold reset.

**Review by leviport — APPROVED** [review]
Confirmed that thelio-b2 now reboots instead of shutting down. I did not notice any keyboard input issues.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
